galaxy:
  - Abregado-rae
  - neighbours:
    - Lanthe
    - Vanik
    - Dentaal

  - Dentaal
  - neighbours:
    - Ghorman

  - Giju
  - neighbours:
    - Ghorman

  - Ghorman
  - neighbours:
    - Vanik
    - Thyferra

  - Vanik
  - neighbours:
    - Wroona
    - Lanthe

  - Thyferra
  - neighbours:
    - Tauber

  - Tauber
  - neighbours:
    - Wroona
    - Sukkult

  - Sukkult
  - neighbours:
    - Wroona

  - Wroona
  - neighbours:
    - Tregillis

  - Tregillis
  - neighbours:
    - Vandelhelm

  - Vandelhelm
  - neighbours:
    - Woostri
    - Alakatha
    - Lanthe

  - Woostri
  - neighbours:
    - Daemen

  - Daemen
  - neighbours:
    - Alakatha

  - Alakatha
  - neighbours:
    - Vondarc

  - Lanthe
  - neighbours:
    - Vondarc

  - Vondarc
  - neighbours:
    - Medth

  - Medth
  - neighbours:
    - Tshindral III

  - Tshindral III
  - neighbours:
    - Medth